#!/bin/bash
#
# steth  OpenStack Software Defined Networking Debuging
#
# chkconfig:   - 98 02
# description: root provides an API to  \
#               * request and configure virtual networks
# Just for CentOS 6.5
### END INIT INFO

. /etc/rc.d/init.d/functions

prog=steth
exec="/usr/bin/$prog-agent"
pidfile="/var/run/$prog/$prog.pid"
logfile="/var/log/$prog/server.log"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog-agent

start() {
    [ -x $exec ] || exit 5
    echo -n $"Starting $prog: "
    daemon --user root --pidfile $pidfile "$exec &>/dev/null & echo \$! > $pidfile"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
